Repository CWorthy-ocean/C-Star, pull requests merged in 2024-12, with the labels that each got.

#176 Build distribution and upload to PyPI
  .github/workflows/pypipublish.yaml
Labels: CI, packaging

#189 Blank releases notes page with template
  .github/PULL_RELEASE_TEMPLATE.md
  docs/index.rst
  docs/releases.rst
Labels: documentation

#190 Add table of which machines C-Star has been tested on
  docs/index.rst
  docs/machines.md
Labels: documentation

#191 Remove expanse from list of tested machines
  docs/machines.md
Labels: documentation

#185 Clarify development status
  README.md
  docs/1_building_a_case_and_exporting_it_as_a_blueprint.ipynb
  docs/2_importing_and_running_a_case_from_a_blueprint.ipynb
  docs/3_restarting_and_continuing_a_case.ipynb
  docs/4_preparing_roms_input_datasets.ipynb
  docs/conf.py
  docs/contributing.md
  docs/disclaimer.md
  docs/index.rst
  docs/installation.md
  docs/machines.md
  docs/terminology.md
Labels: documentation

#193 Added warnings to example notebooks about assuming you're on Perlmutter
  docs/1_building_a_case_and_exporting_it_as_a_blueprint.ipynb
  docs/2_importing_and_running_a_case_from_a_blueprint.ipynb
  docs/3_restarting_and_continuing_a_case.ipynb
  docs/4_preparing_roms_input_datasets.ipynb
Labels: documentation

#192 Release notes for v0.0.1-alpha
  docs/releases.rst
Labels: documentation, releases

#175 Scheduler class
  cstar/base/base_model.py
  cstar/base/component.py
  cstar/base/system.py
  cstar/base/utils.py
  cstar/case.py
  cstar/marbl/base_model.py
  cstar/roms/base_model.py
  cstar/roms/component.py
  cstar/scheduler/job.py
  cstar/system/environment.py
  cstar/system/manager.py
  cstar/system/scheduler.py
  cstar/tests/unit_tests/base/test_base_model.py
  cstar/tests/unit_tests/base/test_system.py
  cstar/tests/unit_tests/base/test_utils.py
  cstar/tests/unit_tests/marbl/test_marbl_base_model.py
  cstar/tests/unit_tests/roms/test_roms_base_model.py
  cstar/tests/unit_tests/scheduler/test_pbs_job.py
  cstar/tests/unit_tests/scheduler/test_scheduler_job.py
  cstar/tests/unit_tests/scheduler/test_slurm_job.py
  cstar/tests/unit_tests/system/test_environment.py
  cstar/tests/unit_tests/system/test_manager.py
  cstar/tests/unit_tests/system/test_scheduler.py
  docs/2_importing_and_running_a_case_from_a_blueprint.ipynb
  docs/3_restarting_and_continuing_a_case.ipynb
  docs/5_handling_jobs_on_hpc_systems.ipynb
  docs/api.rst
  docs/index.rst
  examples/cstar_example.py
Labels: enhancement, internals

#202 include file hash checks for local input datasets
  cstar/base/input_dataset.py
  cstar/base/utils.py
  cstar/tests/unit_tests/base/test_input_dataset.py
  cstar/tests/unit_tests/base/test_utils.py
Labels: user testing
